---
#https://stackoverflow.com/questions/41631770/get-dict-value-from-variable-key-in-ansible/41631874#41631874
#ansible-playbook -i host.txt task.yml --tags="stop" -e "server_name=server2"
- hosts: "{{server_name}}"
  gather_facts: no
  tasks:
    # push server files
    - name: "push {{server_name}}"
      copy:
        src: '{{item.src}}'
        dest: '{{item.dest}}'
        backup: yes
        mode: preserve
      with_items:
        "{{deploy_info[server_name].push}}"
      tags:
        - push
    # init cmd for server
    - name: "init_cmd {{server_name}}"
      shell:
        cmd: '{{item}}'
        warn: False
      with_items:
        '{{deploy_info[server_name].init_cmd}}'
      tags:
        - init_cmd

    # start server
    - name: "start {{server_name}}"
      shell:
        cmd: '{{deploy_info[server_name].start}}'
      register: ret
      tags:
        - start
    - name: "start {{server_name}} print"
      debug: 
        msg: "{{ret.stdout.split('\n')}}"
      tags:
        - start

    # stop server
    - name: "stop {{server_name}}"
      shell:
        cmd: '{{deploy_info[server_name].stop}}'
      register: ret  
      tags:
        - stop
    - name: "stop {{server_name}} print"
      debug: 
        msg: "{{ret.stdout.split('\n')}}"
      tags:
        - stop

    # restart server
    - name: "restart {{server_name}}"
      shell:
        cmd: '{{deploy_info[server_name].restart}}'
      register: ret  
      tags:
        - restart
    - name: "restart {{server_name}} print"
      debug: 
        msg: "{{ret.stdout.split('\n')}}"
      tags:
        - restart

    # status server
    - name: "status {{server_name}}"
      shell:
        cmd: '{{deploy_info[server_name].status}}'
      register: ret  
      tags:
        - status
    - name: "status {{server_name}} print"
      debug: 
        msg: "{{ret.stdout.split('\n')}}"
      tags:
        - status