---
#https://stackoverflow.com/questions/41631770/get-dict-value-from-variable-key-in-ansible/41631874#41631874
#ansible-playbook -i inventory task.yml --tags="stop" -e "server_name=server2"
- hosts: "{{server_name}}"
  gather_facts: no
  tasks:
    # push server files
    - name: "{{server_name}}: copy file"
      copy:
        src: '{{work_dir}}/{{item.src}}'
        dest: '{{item.dest}}'
        backup: no
        mode: preserve
      with_items:
        "{{vars[server_name].cp|default({})}}"
      tags:
        - cp
        - push

    - name: "{{server_name}}: check dest dir"
      file:
        path: '{{item.dest}}/'
        state: directory
      with_items:
        "{{vars[server_name].cp2|default({})}}"
      tags:
        - cp2
        - push

    - name: "{{server_name}}: copy file curt"
      copy:
        src: '{{work_dir}}/{{item.0.src}}/{{item.1}}/'
        dest: '{{item.0.dest}}/{{item.1}}'
        backup: no
        mode: preserve
      with_subelements:
        - "{{vars[server_name].cp2|default({})}}"
        - files
      tags:
        - cp2
        - push

    # push server files
    - name: "{{server_name}}: template file"
      template:
        src: '{{work_dir}}/{{item.src}}'
        dest: '{{item.dest}}'
        mode: preserve
      with_items:
        "{{vars[server_name].cp_t|default({})}}"
      tags:
        - cp_t
        - push

    # init cmd for server
    - name: "{{server_name}}: cmd"
      shell:
        cmd: '{{item}}'
        warn: False
      with_items:
        '{{vars[server_name].cmd|default({})}}'
      tags:
        - cmd

    ###############################################
    # for: remote build
    ###############################################

    - name: "{{server_name}}: fetch file"
      fetch:
        src: '{{item.src}}'
        dest: '{{work_dir}}/{{item.dest}}/'
        backup: no
        remote_src: True
        mode: preserve
        flat: yes
      with_items:
        "{{vars[server_name].fetch|default({})}}"
      tags:
        - fetch

    ###############################################
    # shell: start stop restart status
    ###############################################
    # start server
    - name: "{{server_name}}: start"
      shell:
        cmd: '{{vars[server_name].start}}'
      tags:
        - start

    # stop server
    - name: "{{server_name}}: stop"
      shell:
        cmd: '{{vars[server_name].stop}}'
      tags:
        - stop

    # restart server
    - name: "{{server_name}}: restart"
      shell:
        cmd: '{{vars[server_name].restart}}'
      tags:
        - restart

    # status server
    - name: "{{server_name}}: status"
      shell:
        cmd: '{{vars[server_name].status}}'
      register: ret
      failed_when: "ret.stderr != ''"
      when: vars[server_name].status is defined
      tags:
        - status
    - name: "{{server_name}}: status print"
      debug:
        msg:
          - "{{ret.stdout.split('\n')}}"
          - "{{ret.stderr.split('\n')}}"
      when: vars[server_name].status is defined
      tags:
        - status

    - name: "{{server_name}}: install cron"
      cron:
        name: "{{item.name|default('*')}}"
        minute: "{{item.minute|default('*')}}"
        hour: "{{item.hour|default('*')}}"
        day: "{{item.day|default('*')}}"
        month: "{{item.month|default('*')}}"
        weekday: "{{item.weekday|default('*')}}"
        job: "{{item.job}}"
        state: "{{item.state|regex_replace('remove', 'absent')|regex_replace('install', 'present')}}"
      with_items:
        "{{vars[server_name].crontab|default({})}}"
      tags:
        - install

    - name: "{{server_name}}: remove cron"
      cron:
        name: "{{item.name|default('*')}}"
        minute: "{{item.minute|default('*')}}"
        hour: "{{item.hour|default('*')}}"
        day: "{{item.day|default('*')}}"
        month: "{{item.month|default('*')}}"
        weekday: "{{item.weekday|default('*')}}"
        job: "{{item.job}}"
        state: absent
      with_items:
        "{{vars[server_name].crontab|default({})}}"
      tags:
        - remove
