---
#https://stackoverflow.com/questions/41631770/get-dict-value-from-variable-key-in-ansible/41631874#41631874
#ansible-playbook -i inventory task.yml --tags="stop" -e "server_name=server2 deploy_vars_file=~/.deploy_var.yml"
- hosts: "{{server_name}}"
  gather_facts: no
  vars_files:
    - "{{deploy_vars_file}}"
  vars:
    default_start_file: '{{server_name}}/start.sh'
    start: '{{vars[server_name].start_file|default(default_start_file)}} start'
    stop: '{{vars[server_name].start_file|default(default_start_file)}} stop'
    restart: '{{vars[server_name].start_file|default(default_start_file)}} restart'
    state: '{{vars[server_name].start_file|default(default_start_file)}} state'
  tasks:
    # push server files
    - name: "{{server_name}}: copy files"
      copy:
        src: '{{work_dir}}/{{item.src}}'
        dest: '{{dest_dir|default("")}}/{{item.dest}}'
        backup: no
        mode: preserve
      with_items:
        "{{vars[server_name].cp|default({})}}"
      tags:
        - cp
        - push
        - nover

    - name: "{{server_name}}: copy choose files"
      copy:
        src: '{{work_dir}}/{{item.0.src}}/{{item.1}}'
        dest: '{{dest_dir|default("")}}/{{item.0.dest}}/'
        backup: no
        mode: preserve
      with_subelements:
        - "{{vars[server_name].cp2|default({})}}"
        - files
      tags:
        - cp2
        - push
        - nover

    # push server files
    - name: "{{server_name}}: template files"
      template:
        src: '{{work_dir}}/{{item.src}}'
        dest: '{{dest_dir|default("")}}/{{item.dest}}'
        mode: preserve
      with_items:
        "{{vars[server_name].cp_t|default({})}}"
      tags:
        - cp_t
        - push
        - nover

    # init cmd for server
    - name: "{{server_name}}: cmd"
      shell:
        cmd: '{{item}}'
        warn: False
      register: ret
      when: ret is undefined or ret.rc == 0
      with_items:
        '{{vars[server_name].cmd|default({})}}'
      tags:
        - cmd
        - nover

    ###############################################
    # for: remote build
    ###############################################

    - name: "{{server_name}}: fetch file"
      fetch:
        src: '{{dest_dir|default("")}}/{{item.src}}'
        dest: '{{item.dest}}'
        backup: no
        remote_src: True
        mode: preserve
        flat: yes
      with_items:
        "{{vars[server_name].fetch|default({})}}"
      tags:
        - fetch
        - nover
#  synchronize -a "src=/tmp/client/ dest=/tmp/server mode=pull"
    - name: "{{server_name}}: sync push"
      synchronize:
        src: '{{work_dir}}/{{item.src}}'
        dest: '{{item.dest}}'
        mode: push
      with_items:
        "{{vars[server_name].sync|default({})}}"
      tags:
        - sync
        - nover
    ###############################################
    # shell: start stop restart status
    ###############################################
    # start server
    - name: "{{server_name}}: start"
      shell:
        cmd: 'cd {{dest_dir|default("")}} && {{vars[server_name].start|default(start)}}'
      tags:
        - start
        - nover

    # stop server
    - name: "{{server_name}}: stop"
      shell:
        cmd: 'cd {{dest_dir|default("")}} && {{vars[server_name].stop|default(stop)}}'
      tags:
        - stop
        - nover

    # restart server
    - name: "{{server_name}}: restart"
      shell:
        cmd: 'cd {{dest_dir|default("")}} && {{vars[server_name].restart|default(restart)}}'
      tags:
        - restart
        - nover

    # status server
    - name: "{{server_name}}: state"
      shell:
        cmd: 'cd {{dest_dir|default("")}} && {{vars[server_name].state|default(state)}}'
      register: ret
      failed_when: "ret.stderr != ''"
      ignore_errors: yes
      tags:
        - state
        - nover
    - name: "{{server_name}}: state print"
      debug:
        msg: "{{ret.stdout}}"
      tags:
        - state
        - nover
    ###############################################
    # crontab: install remove
    ###############################################
    - name: "{{server_name}}: install cron"
      cron:
        name: "{{item.name|default('*')}}"
        minute: "{{item.minute|default('*')}}"
        hour: "{{item.hour|default('*')}}"
        day: "{{item.day|default('*')}}"
        month: "{{item.month|default('*')}}"
        weekday: "{{item.weekday|default('*')}}"
        job: "{{item.job}}"
        state: present
      with_items:
        "{{vars[server_name].crontab|default({})}}"
      tags:
        - install
        - nover

    - name: "{{server_name}}: remove cron"
      cron:
        name: "{{item.name|default('*')}}"
        minute: "{{item.minute|default('*')}}"
        hour: "{{item.hour|default('*')}}"
        day: "{{item.day|default('*')}}"
        month: "{{item.month|default('*')}}"
        weekday: "{{item.weekday|default('*')}}"
        job: "{{item.job}}"
        state: absent
      with_items:
        "{{vars[server_name].crontab|default({})}}"
      tags:
        - remove
        - nover
