---
#https://stackoverflow.com/questions/41631770/get-dict-value-from-variable-key-in-ansible/41631874#41631874
#ansible-playbook -i host.txt task.yml --tags="stop" -e "server_name=server2 server_define_file=server.yml"
- hosts: "{{server_name}}"
  gather_facts: no
  vars_files: 
    - "{{server_define_file}}"
    - ~/.bin/key_value.yml
  tasks:
    # - include_vars:
    #     file: "{{server_define_file}}"
    #     name: deploy_info    
    #   tags:
    #   - always

    # push server files
    - name: "push {{server_name}} copy file"
      copy:
        src: '{{work_dir}}/{{item.src}}'
        dest: '{{item.dest}}'
        backup: no
        mode: preserve
      with_items:
        "{{vars[server_name].cp2|default({})}}"
      tags:
        - cp2
        - copy_all

    - name: "push {{server_name}} copy file"
      copy:
        src: '{{work_dir}}/{{item.src}}'
        dest: '{{item.dest}}'
        backup: yes
        mode: preserve
      with_items:
        "{{vars[server_name].cp2|default({})}}"
      tags:
        - cp2_b
        - copy_all_b
    - name: "cp_b check dest dir"
      file:
        path: '{{item.dest}}/'
        state: directory
      with_items:
        - "{{vars[server_name].cp|default({})}}"
      tags:
        - cp
        - copy_all
    - name: "cp check dest dir"
      file:
        path: '{{item.dest}}/'
        state: directory
      with_items:
        - "{{vars[server_name].cp|default({})}}"
      tags:
        - cp_b
        - copy_all_b

    - name: "push {{server_name}} copy file curt"
      copy:
        src: '{{work_dir}}/{{item.0.src}}/{{item.1}}/'
        dest: '{{item.0.dest}}/{{item.1}}'
        backup: no
        mode: preserve
      with_subelements:
        - "{{vars[server_name].cp|default({})}}"
        - files
      tags:
        - cp
        - copy_all


    - name: "push {{server_name}} copy file curt"
      copy:
        src: '{{work_dir}}/{{item.0.src}}/{{item.1}}'
        dest: '{{item.0.dest}}/{{item.1}}'
        backup: yes
        mode: preserve
      with_subelements:
        - "{{vars[server_name].cp|default({})}}"
        - files
      tags:
        - cp_b
        - copy_all_b

    # push server files
    - name: "push {{server_name}} template"
      template:
        src: '{{work_dir}}/{{item.src}}'
        dest: '{{item.dest}}'
        mode: preserve
      with_items:
        "{{vars[server_name].cp_t|default({})}}"
      tags:
        - cp_t
        - copy_all
    - name: "push {{server_name}} template"
      template:
        src: '{{work_dir}}/{{item.src}}'
        dest: '{{item.dest}}'
        backup: yes
        mode: preserve
      with_items:
        "{{vars[server_name].cp_t|default({})}}"
      tags:
        - cp_t_b
        - copy_all_b

    # init cmd for server
    - name: "init {{server_name}}"
      shell:
        cmd: '{{item}}'
        warn: False
      with_items:
        '{{vars[server_name].cmd|default({})}}'
      tags:
        - cmd

    ###############################################
    # supervisor: start stop restart status
    ###############################################
    # start server
    - name: "start {{server_name}}"
      supervisorctl:
        name: "{{server_name}}"
        state: started
        config: "{{vars[server_name].supervisor_conf}}"
      when: vars[server_name].start is undefined
      tags:
        - start

    # stop server
    - name: "stop {{server_name}}"
      supervisorctl:
        name: "{{server_name}}"
        state: stopped
        config: "{{vars[server_name].supervisor_conf}}"
      when: vars[server_name].stop is undefined
      tags:
        - stop


    # restart server
    - name: "restart {{server_name}}"
      supervisorctl:
        name: "{{server_name}}"
        state: restarted
        config: "{{vars[server_name].supervisor_conf}}"
      when: vars[server_name].restart is undefined
      tags:
        - restart

    # status server
    - name: "status {{server_name}}"
      shell:
        cmd: 'supervisorctl -c {{vars[server_name].supervisor_conf}} status {{server_name}}'
      register: ret
      failed_when: "ret.stderr != ''"
      when: vars[server_name].status is undefined
      tags:
        - status
    - name: "status {{server_name}} print"
      debug:
        var: ret.stdout
      when: vars[server_name].status is undefined
      tags:
        - status

    ###############################################
    # for: remote build
    ###############################################

    - name: "fetch {{server_name}} file"
      fetch:
        src: '{{item.src}}'
        dest: '{{work_dir}}/{{item.dest}}/'
        backup: no
        remote_src: True
        mode: preserve
        flat: yes
      with_items:
        "{{vars[server_name].fetch|default({})}}"
      tags:
        - fetch

    ###############################################
    # shell: start stop restart status
    ###############################################
    # start server
    - name: "start {{server_name}}"
      shell:
        cmd: '{{vars[server_name].start}}'
      register: ret
      when: vars[server_name].start is defined
      tags:
        - start
    - name: "start {{server_name}} print"
      debug:
        msg:
          - "{{ret.stdout.split('\n')}}"
          - "{{ret.stderr.split('\n')}}"
      when: vars[server_name].start is defined
      tags:
        - start

    # stop server
    - name: "stop {{server_name}}"
      shell:
        cmd: '{{vars[server_name].stop}}'
      register: ret
      failed_when: "ret.stderr != ''"
      when: vars[server_name].stop is defined
      tags:
        - stop
    - name: "stop {{server_name}} print"
      debug:
        msg:
          - "{{ret.stdout.split('\n')}}"
          - "{{ret.stderr.split('\n')}}"
      when: vars[server_name].stop is defined
      tags:
        - stop

    # restart server
    - name: "restart {{server_name}}"
      shell:
        cmd: '{{vars[server_name].restart}}'
      register: ret
      when: vars[server_name].restart is defined
      tags:
        - restart
    - name: "restart {{server_name}} print"
      debug:
        msg:
          - "{{ret.stdout.split('\n')}}"
          - "{{ret.stderr.split('\n')}}"
      when: vars[server_name].restart is defined
      tags:
        - restart

    # status server
    - name: "status {{server_name}}"
      shell:
        cmd: '{{vars[server_name].status}}'
      register: ret
      failed_when: "ret.stderr != ''"
      when: vars[server_name].status is defined
      tags:
        - status
    - name: "status {{server_name}} print"
      debug:
        msg:
          - "{{ret.stdout.split('\n')}}"
          - "{{ret.stderr.split('\n')}}"
      when: vars[server_name].status is defined
      tags:
        - status

    - name: "install cron {{server_name}}"
      cron:
        name: "{{item.name|default('*')}}"
        minute: "{{item.minute|default('*')}}"
        hour: "{{item.hour|default('*')}}"
        day: "{{item.day|default('*')}}"
        month: "{{item.month|default('*')}}"
        weekday: "{{item.weekday|default('*')}}"
        job: "{{item.job}}"
        state: "{{item.state|regex_replace('remove', 'absent')|regex_replace('install', 'present')}}"
      with_items:
        "{{vars[server_name].crontab|default({})}}"
      tags:
        - install

    - name: "remove cron {{server_name}}"
      cron:
        name: "{{item.name|default('*')}}"
        minute: "{{item.minute|default('*')}}"
        hour: "{{item.hour|default('*')}}"
        day: "{{item.day|default('*')}}"
        month: "{{item.month|default('*')}}"
        weekday: "{{item.weekday|default('*')}}"
        job: "{{item.job}}"
        state: absent
      with_items:
        "{{vars[server_name].crontab|default({})}}"
      tags:
        - remove
