---
#https://stackoverflow.com/questions/41631770/get-dict-value-from-variable-key-in-ansible/41631874#41631874
#ansible-playbook -i host.txt task.yml --tags="stop" -e "server_name=server2 server_define_file=server.yml"
- hosts: "{{server_name}}"
  gather_facts: no
  vars_files:
    - "{{server_define_file}}"
  tasks:
    # push server files
    - name: "push {{server_name}}"
      copy:
        src: '{{work_dir}}/{{item.src}}'
        dest: '{{item.dest}}'
        backup: yes
        mode: preserve
      with_items:
        "{{deploy_info[server_name].push}}"
      tags:
        - push
    # init cmd for server
    - name: "init_cmd {{server_name}}"
      shell:
        cmd: '{{item}}'
        warn: False
      with_items:
        '{{deploy_info[server_name].init_cmd}}'
      tags:
        - init_cmd

    # start server
    - name: "start {{server_name}}"
      supervisorctl:
        name: "{{server_name}}"
        state: started
        config: "{{deploy_info[server_name].supervisor_conf}}"
      tags:
        - start

    # stop server
    - name: "stop {{server_name}}"
      supervisorctl:
        name: "{{server_name}}"
        state: stopped
        config: "{{deploy_info[server_name].supervisor_conf}}"
      tags:
        - stop


    # restart server
    - name: "restart {{server_name}}"
      supervisorctl:
        name: "{{server_name}}"
        state: restarted
        config: "{{deploy_info[server_name].supervisor_conf}}"
      tags:
        - restart

    # status server
    - name: "status {{server_name}}"
      shell:
        cmd: 'supervisorctl -c {{deploy_info[server_name].supervisor_conf}} status {{server_name}}'
      register: ret
      failed_when: "ret.stderr != ''"
      tags:
        - status
    - name: "status {{server_name}} print"
      debug:
        var: ret.stdout
      tags:
        - status

